# generated by datamodel-codegen:
#   filename:  update_user_roles.json

from __future__ import annotations

from typing import Any, Dict, List, Union

from pydantic import BaseModel, Extra


class RoleItem(BaseModel):
    class Config:
        extra = Extra.forbid

    certifier: Dict[str, Any]


class RoleItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    consumer: Dict[str, Any]


class RoleItem2(BaseModel):
    class Config:
        extra = Extra.forbid

    provider: Dict[str, Any]


class AddRole(BaseModel):
    class Config:
        extra = Extra.forbid

    user: str
    role: Union[RoleItem, RoleItem1, RoleItem2]


class UpdateUserRolesParameterItem(BaseModel):
    class Config:
        extra = Extra.forbid

    add_role: AddRole


class RoleItem3(BaseModel):
    class Config:
        extra = Extra.forbid

    certifier: Dict[str, Any]


class RoleItem4(BaseModel):
    class Config:
        extra = Extra.forbid

    consumer: Dict[str, Any]


class RoleItem5(BaseModel):
    class Config:
        extra = Extra.forbid

    provider: Dict[str, Any]


class RemoveRole(BaseModel):
    class Config:
        extra = Extra.forbid

    user: str
    role: Union[RoleItem3, RoleItem4, RoleItem5]


class UpdateUserRolesParameterItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    remove_role: RemoveRole


class UpdateUserRolesParameter(BaseModel):
    __root__: List[Union[UpdateUserRolesParameterItem, UpdateUserRolesParameterItem1]]
